before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
language: python
install: pip install coveralls
python:
  - "2.6"
  - "2.7"
  - "pypy"
  # - "3.2"
  # - "3.3"
script: python setup.py nosetests
after_success: coveralls
notifications:
  email:
    on_success: never
    on_failure: always
