language: python
install:
  - pip install tox coveralls
before_install:
  - uname -a
  - lsb_release -a
  - python --version
  - virtualenv --version
  - pip --version
  - tox --version
script:
  - tox
after_success:
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: always
